### ISSUE TITLE
UI Rework

### ISSUE THREAD

**Issue by thenerdie** [RoBeats-CS/robeats-cs#3]
Kimi will follow up soon.

**Comment by ItzFireable** [comment]
So, this is my part.
I'm currently in the works of designing the new UI, and that requires major rework on how the scripts work because of the variable names, and how the old UI worked.

Currently the UI looks like this:[https://cdn.discordapp.com/attachments/719227386755022992/719274615490216007/RobloxScreenShot20200607_224022015.png](Result Screen), [https://cdn.discordapp.com/attachments/531811357272702986/719312936744779807/RobloxScreenShot20200608_003247740.png](Main Menu)

But as you can see, there's still a lot that needs to be implemented. The plan currently is to remake the screens used in the game.

**Comment by thenerdie** [comment]
This all looks very nice. When you have fully implemented these two screens as you desire (I already implemented one), make a PR.
